[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "unpdf"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "pymupdf4llm",
]

[project.scripts]
unpdf = "unpdf.__main__:main"

[project.optional-dependencies]
dev = [
    "pytest",
]

[tool.black]
line-length = 88
target-version = ['py313']
include = '\.pyi?$'

[tool.pytest.ini_options]
minversion = "7.0"
testpaths = ["tests"]
pythonpath = ["src"]

[tool.mypy]
python_version = "3.13"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true

[tool.bandit]
exclude_dirs = ["tests", "venv"]
skips = ["B101"] # B101: assert_used (often used in tests if tests are not excluded)