name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.13"
  APP_NAME: "unpdf"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v6

    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        # GitHub Action best practice: caching dependencies
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest black bandit mypy pyinstaller
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Check code style with Black
      run: black src/ tests/ --check

    - name: Check static types with mypy
      run: mypy src/ tests/ --install-types --non-interactive

    - name: Check for security vulnerabilities with Bandit
      run: bandit -r src/ tests/ -c pyproject.toml

    - name: Test with pytest
      run: pytest

    - name: Package into a standalone executable
      run: |
        pyinstaller \
            --onefile \
            --console \
            --clean \
            --collect-all pymupdf \
            --name ${{ env.APP_NAME }} \
            src/unpdf/__main__.py